[colors]
[colors.primary]
background = "#1a1a1c"
foreground = "#f2ddc2"

[colors.normal]
black   = "#1a1a1c"
red     = "#f79605"
green   = "#d7be67"
yellow  = "#f5c651"
blue    = "#cbb15b"
magenta = "#e7b211"
cyan    = "#f9e198"
white   = "#fdf5a7"

[colors.bright]
black   = "#545a58"
red     = "#f5dc89"
green   = "#f6e79d"
yellow  = "#fee4a4"
blue    = "#d5d5dc"
magenta = "#f8f8f8"
cyan    = "#e5eae9"
white   = "#f2ddc2"

[colors.cursor]
text   = "#1a1a1c"
cursor = "#f2ddc2"
